version: 2.1

orbs:
  python: circleci/python@0.2.1

dependencies:
    override:
      - pip install tox tox-pyenv
      - pyenv local 2.6.8 2.7.10 3.3.3 3.4.3 3.5.0 3.6.0 3.7.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
            command: |
              . venv/bin/activate
              tox

workflows:
  main:
    jobs:
      - build-and-test

